### ISSUE TITLE
Programatically set a value outside of UI

### ISSUE THREAD

**Issue by ezekielaquino** [pmndrs/leva#164]
is it possible to do something like?

```
const values = useControls({ x: { value: 0 } });

// is there a method to set the value of X?
setValues({ x: 300 });
```

**Comment by guidovizosokognitiv** [comment]
Yes, totally possible!

Here's an example: https://codesandbox.io/s/shy-http-77orp?file=/src/App.js

**Comment by dbismut** [comment]
Yes. We need to write docs for it but have a look at this sandbox:

https://codesandbox.io/s/leva-ui-lm2vb

If you use a function instead of plain objects for inputs, the hook will return an array which second element is a `set` function.

```js
const [values, set] = useControls(() => ({ color: "#fff" }))
```

I'm closing this but feel free to keep asking questions or join our discord channel.
