### ISSUE TITLE
select: value not updating

### ISSUE THREAD

**Issue by sbugert** [pmndrs/leva#165]
I'm using the object variant for the select type like this:

```js
useControls({
  icon: {
    options: { none: '', IconA, IconB },
  },
});
```

My IconA and IconB are functions (React components if that matters). The returned values object changes when selecting a different value but the leva UI does not seem to update. Is this a bug or am I using it wrong?

leva version is 0.7.2
Codesandbox reproducing the issue: https://codesandbox.io/s/keen-lovelace-ip3kx?file=/src/App.js

**Comment by dbismut** [comment]
Oops, this was closed automatically, but it's indeed a bug that `0.7.3` will fix in a few minutes.
It's a bit tricky since the internal `onUpdate` function from this lib behaves a bit like `setState` in the sense that it accepts a function which arguments is the previous value of the input.

Here, since here you pass a function as a value, the internal `onUpdate` gets confused and runs the function (if you look at your example, the value seems to be correct but it doesn't match the functions passed as options, it matches the result of the function).

**Comment by dbismut** [comment]
Btw, I used your example as a story here: https://leva.pmnd.rs/?path=/story/inputs-select--function-as-options

**Comment by sbugert** [comment]
That was fast! Thanks, that fixes it! 🎉
