### ISSUE TITLE
Provide a way to hook into the editing state

### ISSUE THREAD

**Issue by n1ru4l** [pmndrs/leva#181]
For a collaborative application I need to know whether a single value is currently being edited or not. Currently, there is now way to hook into any of the events that might be fired by the inputs such as onFocus/onBlur or onDragStart onDragEnd for the controls such as the Joysticks.

I currently have two potential ideas on how this could be solved.

# Add onChangeStart and onChangeEnd callbacks alongside the onChange callback

The onChangeStart callback should be invoked once an input is focused or a JoyStick/other control is triggered initially (e.g. onMouseDown is triggered). In addition to that the onChangeEnd callbacks should be invoked when an input fires the onBlur event, unmounts, or the onMouseUp event is fired after releasing a JoyStick/other control.

This approach is less flexible, but less complex and requires implementing these callback invocations for all the current input types.

# Add a component dependency injection API

Another solution would be to allow overwriting components that are rendered via the store config. This would allow declaring components that wrap the original leva components, but with additional event handlers attached. A super simple example:

```
const ValueInput = React.useCallback((props) => {
  return <OriginalLevaValueInput {...props} onBlur={() => {
    unlock(props.valueName)
  }} />
}, [])

useControls({ number: { value: 4, ValueInput })
```

However, since onFocus/onBlur events can simply be forwarded to the original components, some of those, such as JoyStick do not have a way to hook into the events declared via the useDrag hook. Thus those components must be refactored to invoke provided callbacks that are passed via props (similar to approach 1).

In general, this approach might be more complex to implement

_____

Summed up both approaches introduce additional maintenance burden as consumers relying on this API might be heavily hit by bugs if one of the start/finish events is not properly invoked.

**Comment by dbismut** [comment]
Hey @n1ru4l thanks for taking the time of putting this together.

As you said `onChangeStart` and `onChangeEnd` would be more straightforward at this point. The only issue is that I don't want to force all components (such as `Image` or custom plugins) to implement those methods, so unless they're specified I guess they would fire before and after each `onChange` frame. Note that we could look at refactoring the `onDrag` hook to take care of this out of the box so that every plugin using drag would benefit from this feature.

Where would the editing state be stored? In user land?
