### ISSUE TITLE
Color picker not visible when in fullscreen mode

### ISSUE THREAD

**Issue by marcelmusiol** [pmndrs/leva#237]
The color picker is not visible when in fullscreen mode: https://266yp.csb.app/

Code: https://codesandbox.io/s/leva-color-picker-fullscreen-266yp?file=/src/App.js 
(fullscreen doesn't work in codesandbox browser panel, so open in a new tab)

Is this a bug or am I doing something wrong in my code?

**Comment by dbismut** [comment]
It looks like this is a proper bug. Interestingly it works in Safari TP...

**Comment by dbismut** [comment]
@marcelmusiol interestingly this sandbox now has fullscreen mode and it works properly.
https://codesandbox.io/s/leva-busy-0kcfx

However your sandbox doesn't, but the answer is because when you pass a container to `useFullScreen`, that container is used full screen, omitting all remaining nodes. Since the color picker is portalled, that portal is ignored.

The fix is to use `document.documentElement` as the fullscreen source.
Here's a demo:

https://codesandbox.io/s/leva-color-picker-fullscreen-forked-guys0

For some reason, I get React error overlay (that should only show in dev mode), but you can dismiss it safely.

**Comment by marcelmusiol** [comment]
@dbismut That makes sense, thanks David!
