### ISSUE TITLE
Range control with same name isn't updated

### ISSUE THREAD

**Issue by mordv** [pmndrs/leva#281]
Two children rendered conditionally, both have `useControls({name: ...})`
[Codesanbox](https://codesandbox.io/s/leva-same-name-control-bug-8i1eo?file=/src/App.js)
![bug](https://user-images.githubusercontent.com/32086218/143788442-9fbb3861-dd71-4b1f-8fa3-6cb484394595.gif)

**Comment by dbismut** [comment]
Hi @mordv thanks for reporting this as it's indeed a UI bug.

When adding an input with an existing path (in your case `name`), Leva doesn't update the value. This is by design and is actually a pretty powerful feature. In other words, you can't expect to have `name` being equal to `0.3` when switching components.

What happens here though is the value `10` being kept while `min` and `max` being changed (as yes, input `settings` do update contrary to values, I agree this is a bit confusing 😅), hence the overflow, but now the PR fixes the overflow, but keeps the value `10`.

It's not a perfect solution I agree, but maybe if you tell me more about the use case I can see if there's another way to make it work.

**Comment by mordv** [comment]
Hi! Thanks for the fix and explanation. 
There's no specific use case, just stumbled upon it accidentally :)
