### ISSUE TITLE
color: Hex colors lose # when in nested folders

### ISSUE THREAD

**Issue by gsimone** [pmndrs/leva#76]
https://leva-git-storybook.pmndrs.vercel.app/?path=/story/misc-folders--nested-folders

**Comment by dbismut** [comment]
That one is a bit tricky since you didn't put a # in front of the initial value.

```js
{
  b: 'ff005b'
}
```

tinycolor is pretty loose when it comes to recognising colors, so it gets recognised as a color, even without the #.

Several options to fix this:
1. don't recognise strings without a leading # as colors.
2. always return the value without the leading # if the initial value is input without it
3. always show return the leading #

I guess we should do options 3, pretty easy fix in theory.

**Comment by gsimone** [comment]
Welp, that's awkward! I think this isn't even a bug, I'll leave it as is and file under "I should pay more attention". We can keep tabs on this and see if somebody else complains 🤷‍♂️

**Comment by dbismut** [comment]
I can do options 3 with no effort.
