### ISSUE TITLE
Adding controls to an already Mounted Panel

### ISSUE THREAD

**Issue by peterjcaulfield** [pmndrs/leva#91]
Hi,

I am trying to add a control to a Panel after it's already mounted.

https://codesandbox.io/s/vigilant-haslett-tzdl4?file=/src/App.js

It seems the hook doesn't register updates when the identity of the config object changes. Can you advise on the best approach for adding controls after the initial panel mount?

Thanks

**Comment by dbismut** [comment]
Hi Peter, the repo is yet under heavy development and leva 0.2.3 is a lot behind. We'll update to 0.3.0 in the following hours.

However there's no out of the box way to do it because recompiling the whole input schema at each render would be too costly, but this is obviously something we need to consider at some point. 

What's the usecase you have in mind?

**Comment by peterjcaulfield** [comment]
Thanks for the quick response. Will keep an eye out for the next release :)

I agree re avoiding recompiling every render. If you don't want to have users ensure a stable identity for the config with changes signalling to recompile, perhaps the hooks could return a refresh function to trigger recompiling when required similar to tweakpanes `pane.refresh()` API.

My use case isn't anything special. I just need to be able to add controls dynamically in some situations as a result of user interaction.

**Comment by dbismut** [comment]
Reason why I'm asking about the usecase is because there's a few things you can do with the existing API, like store switching and setting inputs imperatively. 

Have a look at https://codesandbox.io/s/45bkg for how to do this.

But this won't solve your problem if you need to add inputs imperatively. In that case, we could either pass an optional dependency array to our hooks, either return a function that would imperatively reset the current schema with a new one.

**Comment by peterjcaulfield** [comment]
Thanks for the example will take a look! The dep array would be consistent with how native hooks handle this type of thing so that sounds good to me 👌🏼

**Comment by dbismut** [comment]
Great! Don't hesitate to suggest api ideas or complex use cases. At the moment the lib is unstable api-wise so there's still room for changes and evolutions.

**Comment by dbismut** [comment]
@peterjcaulfield you may want to have a look at #96 👀

**Comment by dbismut** [comment]
Now included in 0.3.3!

**Comment by peterjcaulfield** [comment]
😮   thanks for the quick turn-around in getting this feature added! 🥇 it's a great addition! 👏
